import { useNavigate } from 'react-router-dom';
import { ArrowRight, CalendarClock, CheckCircle2, FileCheck2, FileText, MessageSquare, Sparkles, WandSparkles } from 'lucide-react';
import { differenceInDays, parseISO } from 'date-fns';
import Header from '../components/layout/Header';
import ActionQueue from '../components/dashboard/ActionQueue';
import LoadingSpinner from '../components/ui/LoadingSpinner';
import { useStats } from '../hooks/useStats';
import { useTenders } from '../hooks/useTenders';
import { useAuth } from '../context/AuthContext';
import { formatCurrency, formatDate } from '../lib/formatters';
import type { Tender } from '../types/tender';

const card = 'rounded-2xl border border-border bg-card shadow-card transition-all duration-200 hover:-translate-y-0.5 hover:border-accent/35 hover:shadow-card-hover focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring';

function PriorityCard({ icon, eyebrow, value, label, detail, onClick, tone }: { icon: React.ReactNode; eyebrow: string; value: number; label: string; detail: string; onClick: () => void; tone: 'amber' | 'emerald' | 'sky' }) {
  const tones = { amber: 'bg-amber-500/10 text-amber-700 dark:text-amber-400', emerald: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-400', sky: 'bg-sky-500/10 text-sky-700 dark:text-sky-400' };
  return <button onClick={onClick} className={`${card} group p-4 text-left`}><div className="mb-4 flex items-start justify-between gap-3"><span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[11px] font-bold ${tones[tone]}`}>{icon}{eyebrow}</span><ArrowRight size={15} className="text-muted-foreground transition-transform group-hover:translate-x-0.5 group-hover:text-accent" /></div><p className="text-2xl font-extrabold tabular-nums">{value.toLocaleString()}</p><p className="mt-0.5 text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></button>;
}

function RecommendedTender({ tender }: { tender?: Tender }) {
  const navigate = useNavigate();
  if (!tender) return <div className="rounded-2xl border border-dashed border-border bg-card p-8 text-center"><Sparkles className="mx-auto mb-3 text-muted-foreground" size={24} /><p className="font-semibold">Recommendations are being prepared</p><p className="mt-1 text-sm text-muted-foreground">DRPL will surface the strongest tender match here.</p></div>;
  const score = tender.ai_relevance_score == null ? null : Math.round(tender.ai_relevance_score * 100);
  const days = tender.closing_date ? differenceInDays(parseISO(tender.closing_date), new Date()) : null;
  return <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-card transition-shadow duration-200 hover:shadow-card-hover"><div className="flex flex-col gap-6 p-6 lg:flex-row lg:items-center"><div className="min-w-0 flex-1"><div className="mb-3 flex flex-wrap items-center gap-2">{score != null && <span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs font-bold text-emerald-700 dark:text-emerald-400">{score}% match</span>}<span className="text-xs font-semibold text-muted-foreground">{tender.organisation || tender.department || 'Tender opportunity'}</span></div><h2 className="text-xl font-bold leading-snug">{tender.title}</h2><p className="mt-2 line-clamp-2 text-sm leading-relaxed text-muted-foreground">{tender.ai_summary || 'A strong match based on your tender profile and recent scoring.'}</p><div className="mt-5 flex flex-wrap gap-x-6 gap-y-3 text-sm"><span><span className="text-xs text-muted-foreground">Closing</span><strong className="ml-2">{days != null && days >= 0 ? `${days} days · ` : ''}{formatDate(tender.closing_date)}</strong></span><span><span className="text-xs text-muted-foreground">Estimated value</span><strong className="ml-2">{formatCurrency(tender.estimated_value)}</strong></span></div></div><div className="flex shrink-0 flex-col gap-2 sm:flex-row lg:w-52 lg:flex-col"><button onClick={() => navigate(`/tenders/${tender.id}`)} className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white transition-all hover:-translate-y-0.5 hover:bg-emerald-700 hover:shadow-md">Review tender</button><button onClick={() => navigate(`/tenders/${tender.id}/command-center`)} className="inline-flex items-center justify-center gap-2 rounded-xl border border-border bg-background px-4 py-3 text-sm font-semibold transition-colors hover:border-accent/40 hover:text-accent"><MessageSquare size={15} />Ask DRPL</button></div></div></div>;
}

export default function DashboardPage() {
  const navigate = useNavigate();
  const { auth } = useAuth();
  const { stats, loading } = useStats();
  const { tenders: recommended, loading: recommendationLoading } = useTenders({ score_min: 0.7, status: 'open', sort_by: 'relevance', exclude_expired: true, limit: 1, offset: 0 });
  const { tenders: recent } = useTenders({ status: 'open', sort_by: 'created_at', exclude_expired: true, limit: 1, offset: 0 });
  const rawName = auth.email?.split('@')[0]?.replace(/[._-]+/g, ' ') || 'there';
  const name = rawName.replace(/\b\w/g, (letter) => letter.toUpperCase());
  if (loading) return <><Header title="Home" /><LoadingSpinner /></>;

  return <><Header title={`Good morning, ${name}`} subtitle={`You have ${(stats?.closing_soon_count ?? 0).toLocaleString()} tenders closing this week and ${(stats?.promising_open_count ?? 0).toLocaleString()} promising opportunities to review.`} /><div className="mx-auto w-full max-w-[1600px] space-y-6 p-4 sm:p-6 lg:p-8">
    <div className="grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(280px,1fr)]">
      <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-xs font-extrabold uppercase tracking-[0.14em] text-muted-foreground">Today&apos;s priorities</h2><button onClick={() => navigate('/tenders')} className="text-xs font-semibold text-muted-foreground hover:text-accent">View all</button></div><div className="grid gap-3 sm:grid-cols-3"><PriorityCard icon={<CalendarClock size={13} />} eyebrow="Closing soon" value={stats?.closing_soon_count ?? 0} label="Tenders need attention" detail="Closing within 7 days" tone="amber" onClick={() => navigate('/tenders')} /><PriorityCard icon={<Sparkles size={13} />} eyebrow="Ready to review" value={stats?.promising_open_count ?? 0} label="Promising tenders" detail="Matched to your profile" tone="emerald" onClick={() => navigate('/tenders/view/pursue')} /><PriorityCard icon={<FileCheck2 size={13} />} eyebrow="New arrivals" value={stats?.unscored_tenders ?? 0} label="Tenders to triage" detail="Waiting for a first look" tone="sky" onClick={() => navigate('/tenders/view/new')} /></div></section>
      <section className="space-y-3"><h2 className="text-xs font-extrabold uppercase tracking-[0.14em] text-muted-foreground">Continue working</h2><div className="flex min-h-[151px] flex-col justify-between rounded-2xl border border-border bg-card p-5 shadow-card"><div className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-accent/10 text-accent"><FileText size={18} /></span><div className="min-w-0"><p className="truncate text-sm font-bold">{recent[0]?.title || 'No active tender yet'}</p><p className="mt-0.5 text-xs text-muted-foreground">{recent[0] ? 'Continue your latest tender review' : 'Choose a tender to begin'}</p></div></div><button onClick={() => navigate(recent[0] ? `/tenders/${recent[0].id}` : '/tenders')} className="mt-4 rounded-xl bg-foreground px-4 py-2.5 text-sm font-bold text-background transition-all hover:-translate-y-0.5 hover:opacity-90">{recent[0] ? 'Continue review' : 'Browse tenders'}</button></div></section>
    </div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,2fr)_minmax(300px,1fr)]">
      <section className="space-y-3"><div className="flex items-center justify-between"><h2 className="text-xs font-extrabold uppercase tracking-[0.14em] text-muted-foreground">Recommended for you</h2><button onClick={() => navigate('/tenders/view/pursue')} className="inline-flex items-center gap-1 text-xs font-semibold text-muted-foreground hover:text-accent">See all <ArrowRight size={13} /></button></div>{recommendationLoading ? <div className="h-60 animate-pulse rounded-2xl bg-muted/50" /> : <RecommendedTender tender={recommended[0]} />}<div className="space-y-3 pt-2"><div className="flex items-center justify-between"><h2 className="text-xs font-extrabold uppercase tracking-[0.14em] text-muted-foreground">Work waiting for you</h2><button onClick={() => navigate('/documents')} className="text-xs font-semibold text-muted-foreground hover:text-accent">My work</button></div><ActionQueue /></div></section>
      <aside className="space-y-3"><h2 className="text-xs font-extrabold uppercase tracking-[0.14em] text-muted-foreground">Ask DRPL</h2><div className="rounded-2xl bg-emerald-500 p-5 text-emerald-950 shadow-card"><div className="mb-5 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-white/25"><WandSparkles size={18} /></span><div><p className="font-extrabold">How can I help?</p><p className="text-xs font-medium text-emerald-950/70">Start with a familiar task</p></div></div><div className="space-y-2">{['Explain a tender', 'Prepare a checklist', 'Draft a document', 'Estimate costs'].map((label) => <button key={label} onClick={() => navigate('/command-center')} className="group flex w-full items-center justify-between rounded-xl bg-white/20 px-3.5 py-3 text-left text-sm font-bold transition-colors hover:bg-white/30">{label}<ArrowRight size={14} className="transition-transform group-hover:translate-x-0.5" /></button>)}</div><button onClick={() => navigate('/command-center')} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-extrabold text-emerald-800 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"><MessageSquare size={16} />Open Command Center</button></div><div className="rounded-2xl border border-border bg-card p-5 text-sm shadow-card"><div className="flex items-center gap-2 font-bold"><CheckCircle2 size={17} className="text-emerald-600" />Everything stays connected</div><p className="mt-2 leading-relaxed text-muted-foreground">Open Ask DRPL from a tender to carry its context into the conversation automatically.</p></div></aside>
    </div>
  </div></>;
}
