"""
DRPL Collector - turning a GeM bid PDF into lines a parser can trust.

WHY THIS FILE EXISTS
--------------------
A GeM bid document is machine-generated by TCPDF from a fixed template, and it
is bilingual: every field is printed as ``<Hindi label>/<English label>``
followed by its value. That makes it one of the most parseable documents in
Indian public procurement -- but only after two problems are dealt with, and
both of them are why naive extraction produces garbage.

**1. The Devanagari does not survive text extraction.** GeM's PDFs embed the
Hindi with a non-Unicode font encoding, so ``page.get_text()`` returns mojibake
for it -- ``बड ववरण`` comes back as ``  ``. Verified on 15 live
documents (2026-09-12). The *English* half extracts perfectly every time. So we
drop every non-ASCII byte rather than trying to repair it: the information is
not recoverable and the English label carries the same meaning.

Dropping it leaves a useful artefact. ``ईएमडी विवरण/EMD Detail`` becomes
``/EMD Detail`` -- the slash survives, and it marks exactly where the Hindi
ended and the English began. That slash is the single most valuable anchor in
the document, because it distinguishes a *label* from body text that merely
mentions the same words. ``fields.py`` leans on it hard.

**2. Labels wrap.** A long label is broken across two or three lines by the
PDF's column width, and the break point depends on the label's Hindi length:

    8    %     5<  / MSE
    Relaxation for Years Of Experience and
    Turnover
    Yes | Complete

Line-by-line matching cannot see that label. So we join the normalised lines
into one flat string and match against *that*, which makes wrapping irrelevant.
The cost is that we lose line boundaries -- so we keep both representations and
hand out whichever the caller needs.

WHAT THIS MODULE DOES NOT DO
----------------------------
It does not know a single GeM field name. Everything here is about making the
text faithful and stable; ``fields.py`` owns the format knowledge. Keeping that
split means a GeM template change touches one file.
"""

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass
from typing import Iterable

__all__ = [
    "NormalizedDocument",
    "extract_links",
    "extract_text",
    "is_junk_line",
    "normalize_lines",
    "normalize_text",
    "page_count_of",
    "FURNITURE_PATTERNS",
]


#: Lines that belong to the page, not to the bid. They appear between real
#: content on every page break, and leaving them in lets a page footer land in
#: the middle of a captured value -- e.g. an Item Category that reads
#: "Multimedia Projector 1 / 8 Bid Number: GEM/2026/B/7977682".
#:
#: Each of these was observed on live documents; none is speculative.
#
# Each pattern is matched after a short run of leading non-letters is allowed
# for, because the header's own Hindi leaves a few characters in front of it:
# the live line is ``:/Bid Number: GEM/2026/B/7974647``, not ``Bid Number:``.
# Anchoring these at the true start of the line -- which was the first version
# -- let the whole page header survive into the middle of a captured value.
_LEAD = r"^[^A-Za-z]{0,8}"

FURNITURE_PATTERNS: tuple[re.Pattern, ...] = (
    re.compile(r"^\d+\s*/\s*\d+$"),                      # "3 / 8" page counter
    re.compile(_LEAD + r"Powered by TCPDF", re.I),
    re.compile(r"^[-\s]*Thank You[-\s]*$", re.I),
    re.compile(_LEAD + r"Bid Number\s*:", re.I),         # repeated page header
    re.compile(_LEAD + r"RA Number\s*:", re.I),
    re.compile(_LEAD + r"Dated\s*:\s*\d{2}-\d{2}-\d{4}", re.I),
    re.compile(_LEAD + r"Bid Document\s*$", re.I),
    re.compile(_LEAD + r"RA Document\s*$", re.I),
)

#: A line left behind by the Devanagari with no English on it at all. These sit
#: between a value and the next label whenever GeM wraps a long Hindi label
#: onto its own line, so they land inside the captured value and show up as
#: ``"No '% 2 % 9"``. A line is junk when it carries no word of three or more
#: letters -- which no real GeM value ever fails, and no mojibake run passes.
_REAL_WORD = re.compile(r"[A-Za-z]{3,}")

#: The short values GeM prints that carry no three-letter word. Listing them
#: explicitly is the whole reason this function is safe: the first version
#: simply required a real word, which threw away every ``No`` in the document
#: and reported EMD, MSE relaxation and startup relaxation as unstated on bids
#: that state them plainly.
_SHORT_VALUE = re.compile(r"^(?:yes|no|nil|n/?a|na)\b", re.I)

#: A value that opens with a digit and continues only through the punctuation
#: GeM uses in numbers, dates and times: "1", "22-09-2026 13:00:00", "90".
_NUMERIC_VALUE = re.compile(r"^\d[\d\s.,:%/()\-]*$")


def is_junk_line(line: str) -> bool:
    """True for a line that is only what the stripped Devanagari left behind.

    These appear whenever GeM wraps a long Hindi label onto a line of its own,
    so they sit between a value and the next label and would otherwise be
    joined into the value -- which is how ``MSE Relaxation`` came back as
    ``"No '% 2 % 9"``.
    """
    t = line.strip()
    if not t:
        return True
    if _REAL_WORD.search(t):
        return False
    if _SHORT_VALUE.match(t):
        return False
    if _NUMERIC_VALUE.match(t):
        return False
    return True

def extract_text(data: bytes) -> str:
    """Extract text from PDF bytes, page order preserved.

    PyMuPDF over pypdf on purpose: on the sample of 15 live GeM documents it
    kept the label/value line order intact, while pypdf interleaved table
    columns on the specification pages -- which silently mis-pairs every
    label with its neighbour's value. A parser cannot detect that, so the
    extractor choice has to be right rather than merely available.

    Raises ``ValueError`` on anything that is not a readable PDF, so the caller
    can treat "the portal sent us an HTML error page with a 200" as the
    ordinary event it is.
    """
    if not data:
        raise ValueError("empty document")
    if data[:4] != b"%PDF":
        raise ValueError("not a PDF (no %PDF magic)")

    try:
        import pymupdf  # type: ignore
    except ImportError:  # pragma: no cover - packaging guard
        try:
            import fitz as pymupdf  # type: ignore
        except ImportError as e:  # pragma: no cover
            raise ValueError("no PDF text extractor available (install pymupdf)") from e

    try:
        with pymupdf.open(stream=data, filetype="pdf") as doc:
            return "\n".join(page.get_text() for page in doc)
    except Exception as e:  # noqa: BLE001 - the library raises a zoo of types
        raise ValueError(f"could not read PDF: {e}") from e


def extract_links(data: bytes) -> list[str]:
    """Every hyperlink annotation in the PDF, in page order, de-duplicated.

    GeM does not print the URLs of the buyer's attachments -- the document says
    "Buyer uploaded ATC document Click here to view the file" and hides the
    address in the link annotation. So the scope of work, the BOQ, the price
    breakup and the SLA are reachable only this way. They are the documents an
    analyst most needs, and a collector that ships the bid PDF without them has
    shipped the cover sheet.

    Returns [] rather than raising: a document with no links is ordinary.
    """
    if not data or data[:4] != b"%PDF":
        return []
    try:
        import pymupdf  # type: ignore
    except ImportError:  # pragma: no cover - packaging guard
        try:
            import fitz as pymupdf  # type: ignore
        except ImportError:  # pragma: no cover
            return []

    seen: list[str] = []
    try:
        with pymupdf.open(stream=data, filetype="pdf") as doc:
            for page in doc:
                for link in page.get_links():
                    uri = (link.get("uri") or "").strip()
                    if uri and uri not in seen:
                        seen.append(uri)
    except Exception:  # noqa: BLE001 - links are a bonus, never a failure
        return []
    return seen


def _strip_to_ascii(line: str) -> str:
    """Drop the unrecoverable Devanagari and collapse whitespace.

    NFKC first, and it is not cosmetic. TCPDF sets GeM's English in a font with
    real typographic ligatures, so "Specification" arrives as ``Speci<U+FB01>cation``
    and a bare ASCII filter turns it into ``Specication`` -- in the technical
    specifications block, on every document, which is exactly the text an
    analyst reads. NFKC decomposes those ligatures to their letters first, so
    the word survives. It also folds the curly quotes and non-breaking spaces
    that would otherwise vanish mid-sentence.
    """
    folded = unicodedata.normalize("NFKC", line)
    ascii_only = "".join(ch for ch in folded if 0x20 <= ord(ch) <= 0x7E)
    return re.sub(r"\s+", " ", ascii_only).strip()


def _is_furniture(line: str) -> bool:
    return any(p.match(line) for p in FURNITURE_PATTERNS)


def normalize_lines(text: str) -> list[str]:
    """Raw extracted text -> the meaningful ASCII lines, in order.

    Empty lines and page furniture are dropped. Nothing else is: a value that
    happens to look like noise is still a value, and deciding otherwise is the
    parser's call, not this function's.
    """
    out: list[str] = []
    for raw in text.split("\n"):
        line = _strip_to_ascii(raw)
        if not line or _is_furniture(line):
            continue
        out.append(line)
    return out


def normalize_text(lines: Iterable[str]) -> str:
    """The flat string labels are matched against.

    Joined with single spaces so a label broken across three lines reads as one
    contiguous run. Offsets into this string are what ``fields.py`` returns, so
    it must be built exactly once and shared -- rebuilding it with a different
    join would invalidate every recorded position.
    """
    return " ".join(lines)


@dataclass(frozen=True)
class NormalizedDocument:
    """Both views of one bid document, built together so they cannot drift."""

    #: The meaningful ASCII lines, page order preserved.
    lines: list[str]
    #: ``lines`` joined by single spaces. Label matching happens here.
    flat: str
    #: Page count, useful for drift alarms: a GeM bid document is 5-12 pages,
    #: and a sudden 1-page document usually means an error page rendered as a
    #: PDF rather than a real change in procurement practice.
    page_count: int = 0

    @classmethod
    def from_bytes(cls, data: bytes) -> "NormalizedDocument":
        text = extract_text(data)
        lines = normalize_lines(text)
        return cls(
            lines=lines,
            flat=normalize_text(lines),
            page_count=text.count("\f") + 1 if "\f" in text else _guess_pages(lines),
        )

    @classmethod
    def from_text(cls, text: str) -> "NormalizedDocument":
        """Build from already-extracted text. The seam the tests use."""
        lines = normalize_lines(text)
        return cls(lines=lines, flat=normalize_text(lines), page_count=_guess_pages(lines))

    def __len__(self) -> int:
        return len(self.flat)

    @property
    def is_empty(self) -> bool:
        return not self.flat.strip()


_PAGE_COUNTER = re.compile(r"^(\d+)\s*/\s*(\d+)$")


def _guess_pages(lines: list[str]) -> int:
    """Recover the page count from the "n / m" footer before it was dropped.

    ``normalize_lines`` removes those, so this is only meaningful when called
    on lines that still have them. Returns 0 when unknown, which callers treat
    as "do not alarm on page count" rather than as "zero pages".
    """
    for line in lines:
        m = _PAGE_COUNTER.match(line)
        if m:
            try:
                return int(m.group(2))
            except ValueError:
                return 0
    return 0


def page_count_of(text: str) -> int:
    """Page count read from the raw extracted text, before normalisation."""
    best = 0
    for raw in text.split("\n"):
        m = _PAGE_COUNTER.match(_strip_to_ascii(raw))
        if m:
            try:
                best = max(best, int(m.group(2)))
            except ValueError:
                pass
    return best
